---
version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "niall-byrne"
allow:
  - match:
    dependency_type: "production"
