name: panic_fe-Automation

on:
  push:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set TimeZone
        run: |
          sudo timedatectl set-timezone "America/Toronto"
      - name: Install Node Modules
        run: |
          npm install
      - name: Run Linter
        run: |
          npm run lint
      - name: Sec Test
        run: |
          npm audit --audit-level=moderate
      - name: Unit Tests and Coverage
        run: |
          npm run coverage
      - name: Report Job Status
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"panic_fe: build has failed!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      
      - name: Stage -- Build 
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        run: |
          echo "${REACT_ENV}" > .env.production.local
          npm run build
        env:
          REACT_ENV: ${{ secrets.STAGE_REACT_ENV }}

      - name: Stage -- Automated Deploy        
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.STAGE_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.STAGE_FIREBASE_PROJECT }}        
      - name: Stage -- Report Success
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"panic_fe: automated deploy to stage!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Stage -- Report Failure
        if: ${{ failure() }}
        run: |
          [[ ${REF} == 'refs/heads/develop' ]] && [[ ${EVENT} == 'push' ]] && curl -X POST -H 'Content-type: application/json' --data '{"text":"panic_fe: stage deploy has failed!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          REF: ${{ github.ref }}
          EVENT: ${{ github.event_name }}
      
      - name: Production -- Detect A Release Tag
        if: contains(github.ref, '/tags/v') == true
        run: |
          GIT_DIFF=$(git diff origin/master)
          echo "::set-env name=GIT_DIFF::${GIT_DIFF}"
      - name: Production -- Ignore Non-Release Tags and Branches
        if: contains(github.ref, '/tags/v') != true
        run: |
          GIT_DIFF="not a release"
          echo "::set-env name=GIT_DIFF::${GIT_DIFF}"

      - name: Production -- Prepare Release Content
        if: env.GIT_DIFF == ''
        run: |
          NEWTAG=${GITHUB_REF#refs/tags/}
          echo "::set-env name=NEWTAG::${NEWTAG}"
      - name: Production -- Generate Changelog
        if: env.GIT_DIFF == ''
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Production -- Create Release
        if: env.GIT_DIFF == ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEWTAG }}
          release_name: Release ${{ env.NEWTAG }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false

      - name: Production -- Checkout Master Branch
        if: env.GIT_DIFF == ''
        run: |
          git checkout origin/master
      - name: Production -- Ensure Build Succeeds
        if: env.GIT_DIFF == ''
        run: |
          echo "${REACT_ENV}" > .env.production.local
          npm run build
        env:
          REACT_ENV: ${{ secrets.PRODUCTION_REACT_ENV }}
      - name: Production -- Report Success
        if: env.GIT_DIFF == ''
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"panic_fe: automated release has been created for ${TAG}: https://github.com/niall-byrne/panic-fe/releases\"}" "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TAG: ${{ env.NEWTAG }}
      - name: Production -- Report Failure
        if: ${{ failure() }}
        run: |
          [[ -z ${GIT_DIFF} ]] && curl -X POST -H 'Content-type: application/json' --data '{"text":"panic_fe: automated production release has failed!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GIT_DIFF: ${{ env.GIT_DIFF }}
